#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./scripts/run' >> ~/.aliases
#
# Define Docker Compose command prefix...
set -e

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

function prepare:repo {
    rm -rf wrapper-mingle/vendor
    cd wrapper-mingle
    docker run --rm \
        -v $PWD:/app \
        -v $PWD:/app/packages/mingle \
        -w /app \
        composer install --ignore-platform-reqs --no-scripts
    cd -
}

function setIDS {
    export USER_ID=$(id -u)
    export GROUP_ID=$(id -g)
}

function prepare:container {
    setIDS
    docker compose build
}

function dev:server {
    setIDS
    docker compose up --remove-orphans --force-recreate
}

function ci:server {
    setIDS
    docker compose up -d --remove-orphans --force-recreate
}

function dev:npm {
    setIDS
    docker compose exec webapp bash -c "npm ci ; npm run dev"
}

function test:watch {
    gh workflow run run-e2e-tests.yml && \
    sleep 4 && \
    gh run watch $(gh run list --workflow=run-e2e-tests.yml --limit=1 --json databaseId --jq '.[0].databaseId')
}

function playground:setup() {
    cd playground-ts
    composer install
    npm ci
    touch database/database.sqlite
    php artisan migrate:fresh --seed
}

function playground:run() {
    cd playground-ts
    composer dev
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
