name: Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - next
    paths-ignore:
      - 'docs/**'

jobs:

  pest-tests:
    uses: ./.github/workflows/run-pest-tests.yml

  e2e-tests:
    uses: ./.github/workflows/run-e2e-tests.yml
